
#ifndef FLUIDSOLVER_COMPACTPARTICLECOLLECTION_HPP
#define FLUIDSOLVER_COMPACTPARTICLECOLLECTION_HPP

namespace {
    class CompactParticleCollection {

    };
}

#endif //FLUIDSOLVER_COMPACTPARTICLECOLLECTION_HPP
